// Code generated by protoc-gen-go-pulsar. DO NOT EDIT.
package mycelia

import (
	_ "cosmossdk.io/api/amino"
	fmt "fmt"
	runtime "github.com/cosmos/cosmos-proto/runtime"
	_ "github.com/cosmos/gogoproto/gogoproto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoiface "google.golang.org/protobuf/runtime/protoiface"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	io "io"
	reflect "reflect"
	sync "sync"
)

var (
	md_DataRequest                 protoreflect.MessageDescriptor
	fd_DataRequest_id              protoreflect.FieldDescriptor
	fd_DataRequest_payload         protoreflect.FieldDescriptor
	fd_DataRequest_status          protoreflect.FieldDescriptor
	fd_DataRequest_commit_count    protoreflect.FieldDescriptor
	fd_DataRequest_signature_count protoreflect.FieldDescriptor
)

func init() {
	file_mycelia_mycelia_types_proto_init()
	md_DataRequest = File_mycelia_mycelia_types_proto.Messages().ByName("DataRequest")
	fd_DataRequest_id = md_DataRequest.Fields().ByName("id")
	fd_DataRequest_payload = md_DataRequest.Fields().ByName("payload")
	fd_DataRequest_status = md_DataRequest.Fields().ByName("status")
	fd_DataRequest_commit_count = md_DataRequest.Fields().ByName("commit_count")
	fd_DataRequest_signature_count = md_DataRequest.Fields().ByName("signature_count")
}

var _ protoreflect.Message = (*fastReflection_DataRequest)(nil)

type fastReflection_DataRequest DataRequest

func (x *DataRequest) ProtoReflect() protoreflect.Message {
	return (*fastReflection_DataRequest)(x)
}

func (x *DataRequest) slowProtoReflect() protoreflect.Message {
	mi := &file_mycelia_mycelia_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_DataRequest_messageType fastReflection_DataRequest_messageType
var _ protoreflect.MessageType = fastReflection_DataRequest_messageType{}

type fastReflection_DataRequest_messageType struct{}

func (x fastReflection_DataRequest_messageType) Zero() protoreflect.Message {
	return (*fastReflection_DataRequest)(nil)
}
func (x fastReflection_DataRequest_messageType) New() protoreflect.Message {
	return new(fastReflection_DataRequest)
}
func (x fastReflection_DataRequest_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_DataRequest
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_DataRequest) Descriptor() protoreflect.MessageDescriptor {
	return md_DataRequest
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_DataRequest) Type() protoreflect.MessageType {
	return _fastReflection_DataRequest_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_DataRequest) New() protoreflect.Message {
	return new(fastReflection_DataRequest)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_DataRequest) Interface() protoreflect.ProtoMessage {
	return (*DataRequest)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_DataRequest) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.Id != uint64(0) {
		value := protoreflect.ValueOfUint64(x.Id)
		if !f(fd_DataRequest_id, value) {
			return
		}
	}
	if x.Payload != nil {
		value := protoreflect.ValueOfMessage(x.Payload.ProtoReflect())
		if !f(fd_DataRequest_payload, value) {
			return
		}
	}
	if x.Status != 0 {
		value := protoreflect.ValueOfEnum((protoreflect.EnumNumber)(x.Status))
		if !f(fd_DataRequest_status, value) {
			return
		}
	}
	if x.CommitCount != uint64(0) {
		value := protoreflect.ValueOfUint64(x.CommitCount)
		if !f(fd_DataRequest_commit_count, value) {
			return
		}
	}
	if x.SignatureCount != uint64(0) {
		value := protoreflect.ValueOfUint64(x.SignatureCount)
		if !f(fd_DataRequest_signature_count, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_DataRequest) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "mycelia.mycelia.DataRequest.id":
		return x.Id != uint64(0)
	case "mycelia.mycelia.DataRequest.payload":
		return x.Payload != nil
	case "mycelia.mycelia.DataRequest.status":
		return x.Status != 0
	case "mycelia.mycelia.DataRequest.commit_count":
		return x.CommitCount != uint64(0)
	case "mycelia.mycelia.DataRequest.signature_count":
		return x.SignatureCount != uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: mycelia.mycelia.DataRequest"))
		}
		panic(fmt.Errorf("message mycelia.mycelia.DataRequest does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_DataRequest) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "mycelia.mycelia.DataRequest.id":
		x.Id = uint64(0)
	case "mycelia.mycelia.DataRequest.payload":
		x.Payload = nil
	case "mycelia.mycelia.DataRequest.status":
		x.Status = 0
	case "mycelia.mycelia.DataRequest.commit_count":
		x.CommitCount = uint64(0)
	case "mycelia.mycelia.DataRequest.signature_count":
		x.SignatureCount = uint64(0)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: mycelia.mycelia.DataRequest"))
		}
		panic(fmt.Errorf("message mycelia.mycelia.DataRequest does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_DataRequest) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "mycelia.mycelia.DataRequest.id":
		value := x.Id
		return protoreflect.ValueOfUint64(value)
	case "mycelia.mycelia.DataRequest.payload":
		value := x.Payload
		return protoreflect.ValueOfMessage(value.ProtoReflect())
	case "mycelia.mycelia.DataRequest.status":
		value := x.Status
		return protoreflect.ValueOfEnum((protoreflect.EnumNumber)(value))
	case "mycelia.mycelia.DataRequest.commit_count":
		value := x.CommitCount
		return protoreflect.ValueOfUint64(value)
	case "mycelia.mycelia.DataRequest.signature_count":
		value := x.SignatureCount
		return protoreflect.ValueOfUint64(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: mycelia.mycelia.DataRequest"))
		}
		panic(fmt.Errorf("message mycelia.mycelia.DataRequest does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_DataRequest) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "mycelia.mycelia.DataRequest.id":
		x.Id = value.Uint()
	case "mycelia.mycelia.DataRequest.payload":
		x.Payload = value.Message().Interface().(*PayLoad)
	case "mycelia.mycelia.DataRequest.status":
		x.Status = (STATUS)(value.Enum())
	case "mycelia.mycelia.DataRequest.commit_count":
		x.CommitCount = value.Uint()
	case "mycelia.mycelia.DataRequest.signature_count":
		x.SignatureCount = value.Uint()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: mycelia.mycelia.DataRequest"))
		}
		panic(fmt.Errorf("message mycelia.mycelia.DataRequest does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_DataRequest) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "mycelia.mycelia.DataRequest.payload":
		if x.Payload == nil {
			x.Payload = new(PayLoad)
		}
		return protoreflect.ValueOfMessage(x.Payload.ProtoReflect())
	case "mycelia.mycelia.DataRequest.id":
		panic(fmt.Errorf("field id of message mycelia.mycelia.DataRequest is not mutable"))
	case "mycelia.mycelia.DataRequest.status":
		panic(fmt.Errorf("field status of message mycelia.mycelia.DataRequest is not mutable"))
	case "mycelia.mycelia.DataRequest.commit_count":
		panic(fmt.Errorf("field commit_count of message mycelia.mycelia.DataRequest is not mutable"))
	case "mycelia.mycelia.DataRequest.signature_count":
		panic(fmt.Errorf("field signature_count of message mycelia.mycelia.DataRequest is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: mycelia.mycelia.DataRequest"))
		}
		panic(fmt.Errorf("message mycelia.mycelia.DataRequest does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_DataRequest) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "mycelia.mycelia.DataRequest.id":
		return protoreflect.ValueOfUint64(uint64(0))
	case "mycelia.mycelia.DataRequest.payload":
		m := new(PayLoad)
		return protoreflect.ValueOfMessage(m.ProtoReflect())
	case "mycelia.mycelia.DataRequest.status":
		return protoreflect.ValueOfEnum(0)
	case "mycelia.mycelia.DataRequest.commit_count":
		return protoreflect.ValueOfUint64(uint64(0))
	case "mycelia.mycelia.DataRequest.signature_count":
		return protoreflect.ValueOfUint64(uint64(0))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: mycelia.mycelia.DataRequest"))
		}
		panic(fmt.Errorf("message mycelia.mycelia.DataRequest does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_DataRequest) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in mycelia.mycelia.DataRequest", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_DataRequest) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_DataRequest) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_DataRequest) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_DataRequest) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*DataRequest)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.Id != 0 {
			n += 1 + runtime.Sov(uint64(x.Id))
		}
		if x.Payload != nil {
			l = options.Size(x.Payload)
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.Status != 0 {
			n += 1 + runtime.Sov(uint64(x.Status))
		}
		if x.CommitCount != 0 {
			n += 1 + runtime.Sov(uint64(x.CommitCount))
		}
		if x.SignatureCount != 0 {
			n += 1 + runtime.Sov(uint64(x.SignatureCount))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*DataRequest)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if x.SignatureCount != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.SignatureCount))
			i--
			dAtA[i] = 0x28
		}
		if x.CommitCount != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.CommitCount))
			i--
			dAtA[i] = 0x20
		}
		if x.Status != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Status))
			i--
			dAtA[i] = 0x18
		}
		if x.Payload != nil {
			encoded, err := options.Marshal(x.Payload)
			if err != nil {
				return protoiface.MarshalOutput{
					NoUnkeyedLiterals: input.NoUnkeyedLiterals,
					Buf:               input.Buf,
				}, err
			}
			i -= len(encoded)
			copy(dAtA[i:], encoded)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(encoded)))
			i--
			dAtA[i] = 0x12
		}
		if x.Id != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.Id))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*DataRequest)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: DataRequest: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: DataRequest: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
				}
				x.Id = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Id |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
				}
				var msglen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					msglen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if msglen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + msglen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if x.Payload == nil {
					x.Payload = &PayLoad{}
				}
				if err := options.Unmarshal(dAtA[iNdEx:postIndex], x.Payload); err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				iNdEx = postIndex
			case 3:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
				}
				x.Status = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.Status |= STATUS(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 4:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field CommitCount", wireType)
				}
				x.CommitCount = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.CommitCount |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 5:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field SignatureCount", wireType)
				}
				x.SignatureCount = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.SignatureCount |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

var (
	md_PayLoad                   protoreflect.MessageDescriptor
	fd_PayLoad_chain_id          protoreflect.FieldDescriptor
	fd_PayLoad_contract_address  protoreflect.FieldDescriptor
	fd_PayLoad_function_signture protoreflect.FieldDescriptor
	fd_PayLoad_output            protoreflect.FieldDescriptor
)

func init() {
	file_mycelia_mycelia_types_proto_init()
	md_PayLoad = File_mycelia_mycelia_types_proto.Messages().ByName("PayLoad")
	fd_PayLoad_chain_id = md_PayLoad.Fields().ByName("chain_id")
	fd_PayLoad_contract_address = md_PayLoad.Fields().ByName("contract_address")
	fd_PayLoad_function_signture = md_PayLoad.Fields().ByName("function_signture")
	fd_PayLoad_output = md_PayLoad.Fields().ByName("output")
}

var _ protoreflect.Message = (*fastReflection_PayLoad)(nil)

type fastReflection_PayLoad PayLoad

func (x *PayLoad) ProtoReflect() protoreflect.Message {
	return (*fastReflection_PayLoad)(x)
}

func (x *PayLoad) slowProtoReflect() protoreflect.Message {
	mi := &file_mycelia_mycelia_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

var _fastReflection_PayLoad_messageType fastReflection_PayLoad_messageType
var _ protoreflect.MessageType = fastReflection_PayLoad_messageType{}

type fastReflection_PayLoad_messageType struct{}

func (x fastReflection_PayLoad_messageType) Zero() protoreflect.Message {
	return (*fastReflection_PayLoad)(nil)
}
func (x fastReflection_PayLoad_messageType) New() protoreflect.Message {
	return new(fastReflection_PayLoad)
}
func (x fastReflection_PayLoad_messageType) Descriptor() protoreflect.MessageDescriptor {
	return md_PayLoad
}

// Descriptor returns message descriptor, which contains only the protobuf
// type information for the message.
func (x *fastReflection_PayLoad) Descriptor() protoreflect.MessageDescriptor {
	return md_PayLoad
}

// Type returns the message type, which encapsulates both Go and protobuf
// type information. If the Go type information is not needed,
// it is recommended that the message descriptor be used instead.
func (x *fastReflection_PayLoad) Type() protoreflect.MessageType {
	return _fastReflection_PayLoad_messageType
}

// New returns a newly allocated and mutable empty message.
func (x *fastReflection_PayLoad) New() protoreflect.Message {
	return new(fastReflection_PayLoad)
}

// Interface unwraps the message reflection interface and
// returns the underlying ProtoMessage interface.
func (x *fastReflection_PayLoad) Interface() protoreflect.ProtoMessage {
	return (*PayLoad)(x)
}

// Range iterates over every populated field in an undefined order,
// calling f for each field descriptor and value encountered.
// Range returns immediately if f returns false.
// While iterating, mutating operations may only be performed
// on the current field descriptor.
func (x *fastReflection_PayLoad) Range(f func(protoreflect.FieldDescriptor, protoreflect.Value) bool) {
	if x.ChainId != uint64(0) {
		value := protoreflect.ValueOfUint64(x.ChainId)
		if !f(fd_PayLoad_chain_id, value) {
			return
		}
	}
	if x.ContractAddress != "" {
		value := protoreflect.ValueOfString(x.ContractAddress)
		if !f(fd_PayLoad_contract_address, value) {
			return
		}
	}
	if x.FunctionSignture != "" {
		value := protoreflect.ValueOfString(x.FunctionSignture)
		if !f(fd_PayLoad_function_signture, value) {
			return
		}
	}
	if len(x.Output) != 0 {
		value := protoreflect.ValueOfBytes(x.Output)
		if !f(fd_PayLoad_output, value) {
			return
		}
	}
}

// Has reports whether a field is populated.
//
// Some fields have the property of nullability where it is possible to
// distinguish between the default value of a field and whether the field
// was explicitly populated with the default value. Singular message fields,
// member fields of a oneof, and proto2 scalar fields are nullable. Such
// fields are populated only if explicitly set.
//
// In other cases (aside from the nullable cases above),
// a proto3 scalar field is populated if it contains a non-zero value, and
// a repeated field is populated if it is non-empty.
func (x *fastReflection_PayLoad) Has(fd protoreflect.FieldDescriptor) bool {
	switch fd.FullName() {
	case "mycelia.mycelia.PayLoad.chain_id":
		return x.ChainId != uint64(0)
	case "mycelia.mycelia.PayLoad.contract_address":
		return x.ContractAddress != ""
	case "mycelia.mycelia.PayLoad.function_signture":
		return x.FunctionSignture != ""
	case "mycelia.mycelia.PayLoad.output":
		return len(x.Output) != 0
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: mycelia.mycelia.PayLoad"))
		}
		panic(fmt.Errorf("message mycelia.mycelia.PayLoad does not contain field %s", fd.FullName()))
	}
}

// Clear clears the field such that a subsequent Has call reports false.
//
// Clearing an extension field clears both the extension type and value
// associated with the given field number.
//
// Clear is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PayLoad) Clear(fd protoreflect.FieldDescriptor) {
	switch fd.FullName() {
	case "mycelia.mycelia.PayLoad.chain_id":
		x.ChainId = uint64(0)
	case "mycelia.mycelia.PayLoad.contract_address":
		x.ContractAddress = ""
	case "mycelia.mycelia.PayLoad.function_signture":
		x.FunctionSignture = ""
	case "mycelia.mycelia.PayLoad.output":
		x.Output = nil
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: mycelia.mycelia.PayLoad"))
		}
		panic(fmt.Errorf("message mycelia.mycelia.PayLoad does not contain field %s", fd.FullName()))
	}
}

// Get retrieves the value for a field.
//
// For unpopulated scalars, it returns the default value, where
// the default value of a bytes scalar is guaranteed to be a copy.
// For unpopulated composite types, it returns an empty, read-only view
// of the value; to obtain a mutable reference, use Mutable.
func (x *fastReflection_PayLoad) Get(descriptor protoreflect.FieldDescriptor) protoreflect.Value {
	switch descriptor.FullName() {
	case "mycelia.mycelia.PayLoad.chain_id":
		value := x.ChainId
		return protoreflect.ValueOfUint64(value)
	case "mycelia.mycelia.PayLoad.contract_address":
		value := x.ContractAddress
		return protoreflect.ValueOfString(value)
	case "mycelia.mycelia.PayLoad.function_signture":
		value := x.FunctionSignture
		return protoreflect.ValueOfString(value)
	case "mycelia.mycelia.PayLoad.output":
		value := x.Output
		return protoreflect.ValueOfBytes(value)
	default:
		if descriptor.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: mycelia.mycelia.PayLoad"))
		}
		panic(fmt.Errorf("message mycelia.mycelia.PayLoad does not contain field %s", descriptor.FullName()))
	}
}

// Set stores the value for a field.
//
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType.
// When setting a composite type, it is unspecified whether the stored value
// aliases the source's memory in any way. If the composite value is an
// empty, read-only value, then it panics.
//
// Set is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PayLoad) Set(fd protoreflect.FieldDescriptor, value protoreflect.Value) {
	switch fd.FullName() {
	case "mycelia.mycelia.PayLoad.chain_id":
		x.ChainId = value.Uint()
	case "mycelia.mycelia.PayLoad.contract_address":
		x.ContractAddress = value.Interface().(string)
	case "mycelia.mycelia.PayLoad.function_signture":
		x.FunctionSignture = value.Interface().(string)
	case "mycelia.mycelia.PayLoad.output":
		x.Output = value.Bytes()
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: mycelia.mycelia.PayLoad"))
		}
		panic(fmt.Errorf("message mycelia.mycelia.PayLoad does not contain field %s", fd.FullName()))
	}
}

// Mutable returns a mutable reference to a composite type.
//
// If the field is unpopulated, it may allocate a composite value.
// For a field belonging to a oneof, it implicitly clears any other field
// that may be currently set within the same oneof.
// For extension fields, it implicitly stores the provided ExtensionType
// if not already stored.
// It panics if the field does not contain a composite type.
//
// Mutable is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PayLoad) Mutable(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "mycelia.mycelia.PayLoad.chain_id":
		panic(fmt.Errorf("field chain_id of message mycelia.mycelia.PayLoad is not mutable"))
	case "mycelia.mycelia.PayLoad.contract_address":
		panic(fmt.Errorf("field contract_address of message mycelia.mycelia.PayLoad is not mutable"))
	case "mycelia.mycelia.PayLoad.function_signture":
		panic(fmt.Errorf("field function_signture of message mycelia.mycelia.PayLoad is not mutable"))
	case "mycelia.mycelia.PayLoad.output":
		panic(fmt.Errorf("field output of message mycelia.mycelia.PayLoad is not mutable"))
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: mycelia.mycelia.PayLoad"))
		}
		panic(fmt.Errorf("message mycelia.mycelia.PayLoad does not contain field %s", fd.FullName()))
	}
}

// NewField returns a new value that is assignable to the field
// for the given descriptor. For scalars, this returns the default value.
// For lists, maps, and messages, this returns a new, empty, mutable value.
func (x *fastReflection_PayLoad) NewField(fd protoreflect.FieldDescriptor) protoreflect.Value {
	switch fd.FullName() {
	case "mycelia.mycelia.PayLoad.chain_id":
		return protoreflect.ValueOfUint64(uint64(0))
	case "mycelia.mycelia.PayLoad.contract_address":
		return protoreflect.ValueOfString("")
	case "mycelia.mycelia.PayLoad.function_signture":
		return protoreflect.ValueOfString("")
	case "mycelia.mycelia.PayLoad.output":
		return protoreflect.ValueOfBytes(nil)
	default:
		if fd.IsExtension() {
			panic(fmt.Errorf("proto3 declared messages do not support extensions: mycelia.mycelia.PayLoad"))
		}
		panic(fmt.Errorf("message mycelia.mycelia.PayLoad does not contain field %s", fd.FullName()))
	}
}

// WhichOneof reports which field within the oneof is populated,
// returning nil if none are populated.
// It panics if the oneof descriptor does not belong to this message.
func (x *fastReflection_PayLoad) WhichOneof(d protoreflect.OneofDescriptor) protoreflect.FieldDescriptor {
	switch d.FullName() {
	default:
		panic(fmt.Errorf("%s is not a oneof field in mycelia.mycelia.PayLoad", d.FullName()))
	}
	panic("unreachable")
}

// GetUnknown retrieves the entire list of unknown fields.
// The caller may only mutate the contents of the RawFields
// if the mutated bytes are stored back into the message with SetUnknown.
func (x *fastReflection_PayLoad) GetUnknown() protoreflect.RawFields {
	return x.unknownFields
}

// SetUnknown stores an entire list of unknown fields.
// The raw fields must be syntactically valid according to the wire format.
// An implementation may panic if this is not the case.
// Once stored, the caller must not mutate the content of the RawFields.
// An empty RawFields may be passed to clear the fields.
//
// SetUnknown is a mutating operation and unsafe for concurrent use.
func (x *fastReflection_PayLoad) SetUnknown(fields protoreflect.RawFields) {
	x.unknownFields = fields
}

// IsValid reports whether the message is valid.
//
// An invalid message is an empty, read-only value.
//
// An invalid message often corresponds to a nil pointer of the concrete
// message type, but the details are implementation dependent.
// Validity is not part of the protobuf data model, and may not
// be preserved in marshaling or other operations.
func (x *fastReflection_PayLoad) IsValid() bool {
	return x != nil
}

// ProtoMethods returns optional fastReflectionFeature-path implementations of various operations.
// This method may return nil.
//
// The returned methods type is identical to
// "google.golang.org/protobuf/runtime/protoiface".Methods.
// Consult the protoiface package documentation for details.
func (x *fastReflection_PayLoad) ProtoMethods() *protoiface.Methods {
	size := func(input protoiface.SizeInput) protoiface.SizeOutput {
		x := input.Message.Interface().(*PayLoad)
		if x == nil {
			return protoiface.SizeOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Size:              0,
			}
		}
		options := runtime.SizeInputToOptions(input)
		_ = options
		var n int
		var l int
		_ = l
		if x.ChainId != 0 {
			n += 1 + runtime.Sov(uint64(x.ChainId))
		}
		l = len(x.ContractAddress)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.FunctionSignture)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		l = len(x.Output)
		if l > 0 {
			n += 1 + l + runtime.Sov(uint64(l))
		}
		if x.unknownFields != nil {
			n += len(x.unknownFields)
		}
		return protoiface.SizeOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Size:              n,
		}
	}

	marshal := func(input protoiface.MarshalInput) (protoiface.MarshalOutput, error) {
		x := input.Message.Interface().(*PayLoad)
		if x == nil {
			return protoiface.MarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Buf:               input.Buf,
			}, nil
		}
		options := runtime.MarshalInputToOptions(input)
		_ = options
		size := options.Size(x)
		dAtA := make([]byte, size)
		i := len(dAtA)
		_ = i
		var l int
		_ = l
		if x.unknownFields != nil {
			i -= len(x.unknownFields)
			copy(dAtA[i:], x.unknownFields)
		}
		if len(x.Output) > 0 {
			i -= len(x.Output)
			copy(dAtA[i:], x.Output)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.Output)))
			i--
			dAtA[i] = 0x22
		}
		if len(x.FunctionSignture) > 0 {
			i -= len(x.FunctionSignture)
			copy(dAtA[i:], x.FunctionSignture)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.FunctionSignture)))
			i--
			dAtA[i] = 0x1a
		}
		if len(x.ContractAddress) > 0 {
			i -= len(x.ContractAddress)
			copy(dAtA[i:], x.ContractAddress)
			i = runtime.EncodeVarint(dAtA, i, uint64(len(x.ContractAddress)))
			i--
			dAtA[i] = 0x12
		}
		if x.ChainId != 0 {
			i = runtime.EncodeVarint(dAtA, i, uint64(x.ChainId))
			i--
			dAtA[i] = 0x8
		}
		if input.Buf != nil {
			input.Buf = append(input.Buf, dAtA...)
		} else {
			input.Buf = dAtA
		}
		return protoiface.MarshalOutput{
			NoUnkeyedLiterals: input.NoUnkeyedLiterals,
			Buf:               input.Buf,
		}, nil
	}
	unmarshal := func(input protoiface.UnmarshalInput) (protoiface.UnmarshalOutput, error) {
		x := input.Message.Interface().(*PayLoad)
		if x == nil {
			return protoiface.UnmarshalOutput{
				NoUnkeyedLiterals: input.NoUnkeyedLiterals,
				Flags:             input.Flags,
			}, nil
		}
		options := runtime.UnmarshalInputToOptions(input)
		_ = options
		dAtA := input.Buf
		l := len(dAtA)
		iNdEx := 0
		for iNdEx < l {
			preIndex := iNdEx
			var wire uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
				}
				if iNdEx >= l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				wire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			fieldNum := int32(wire >> 3)
			wireType := int(wire & 0x7)
			if wireType == 4 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: PayLoad: wiretype end group for non-group")
			}
			if fieldNum <= 0 {
				return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: PayLoad: illegal tag %d (wire type %d)", fieldNum, wire)
			}
			switch fieldNum {
			case 1:
				if wireType != 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
				}
				x.ChainId = 0
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					x.ChainId |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
			case 2:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field ContractAddress", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.ContractAddress = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 3:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field FunctionSignture", wireType)
				}
				var stringLen uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					stringLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				intStringLen := int(stringLen)
				if intStringLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + intStringLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.FunctionSignture = string(dAtA[iNdEx:postIndex])
				iNdEx = postIndex
			case 4:
				if wireType != 2 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, fmt.Errorf("proto: wrong wireType = %d for field Output", wireType)
				}
				var byteLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrIntOverflow
					}
					if iNdEx >= l {
						return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					byteLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if byteLen < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				postIndex := iNdEx + byteLen
				if postIndex < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if postIndex > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				x.Output = append(x.Output[:0], dAtA[iNdEx:postIndex]...)
				if x.Output == nil {
					x.Output = []byte{}
				}
				iNdEx = postIndex
			default:
				iNdEx = preIndex
				skippy, err := runtime.Skip(dAtA[iNdEx:])
				if err != nil {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, err
				}
				if (skippy < 0) || (iNdEx+skippy) < 0 {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, runtime.ErrInvalidLength
				}
				if (iNdEx + skippy) > l {
					return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
				}
				if !options.DiscardUnknown {
					x.unknownFields = append(x.unknownFields, dAtA[iNdEx:iNdEx+skippy]...)
				}
				iNdEx += skippy
			}
		}

		if iNdEx > l {
			return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, io.ErrUnexpectedEOF
		}
		return protoiface.UnmarshalOutput{NoUnkeyedLiterals: input.NoUnkeyedLiterals, Flags: input.Flags}, nil
	}
	return &protoiface.Methods{
		NoUnkeyedLiterals: struct{}{},
		Flags:             protoiface.SupportMarshalDeterministic | protoiface.SupportUnmarshalDiscardUnknown,
		Size:              size,
		Marshal:           marshal,
		Unmarshal:         unmarshal,
		Merge:             nil,
		CheckInitialized:  nil,
	}
}

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.0
// 	protoc        (unknown)
// source: mycelia/mycelia/types.proto

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type STATUS int32

const (
	STATUS_REQUESTED STATUS = 0
	STATUS_ATTESTED  STATUS = 1
	STATUS_SIGNED    STATUS = 2
)

// Enum value maps for STATUS.
var (
	STATUS_name = map[int32]string{
		0: "REQUESTED",
		1: "ATTESTED",
		2: "SIGNED",
	}
	STATUS_value = map[string]int32{
		"REQUESTED": 0,
		"ATTESTED":  1,
		"SIGNED":    2,
	}
)

func (x STATUS) Enum() *STATUS {
	p := new(STATUS)
	*p = x
	return p
}

func (x STATUS) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (STATUS) Descriptor() protoreflect.EnumDescriptor {
	return file_mycelia_mycelia_types_proto_enumTypes[0].Descriptor()
}

func (STATUS) Type() protoreflect.EnumType {
	return &file_mycelia_mycelia_types_proto_enumTypes[0]
}

func (x STATUS) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use STATUS.Descriptor instead.
func (STATUS) EnumDescriptor() ([]byte, []int) {
	return file_mycelia_mycelia_types_proto_rawDescGZIP(), []int{0}
}

// DataRequests defines the data requests posted to the state.
type DataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload        *PayLoad `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Status         STATUS   `protobuf:"varint,3,opt,name=status,proto3,enum=mycelia.mycelia.STATUS" json:"status,omitempty"`
	CommitCount    uint64   `protobuf:"varint,4,opt,name=commit_count,json=commitCount,proto3" json:"commit_count,omitempty"`
	SignatureCount uint64   `protobuf:"varint,5,opt,name=signature_count,json=signatureCount,proto3" json:"signature_count,omitempty"`
}

func (x *DataRequest) Reset() {
	*x = DataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mycelia_mycelia_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataRequest) ProtoMessage() {}

// Deprecated: Use DataRequest.ProtoReflect.Descriptor instead.
func (*DataRequest) Descriptor() ([]byte, []int) {
	return file_mycelia_mycelia_types_proto_rawDescGZIP(), []int{0}
}

func (x *DataRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DataRequest) GetPayload() *PayLoad {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DataRequest) GetStatus() STATUS {
	if x != nil {
		return x.Status
	}
	return STATUS_REQUESTED
}

func (x *DataRequest) GetCommitCount() uint64 {
	if x != nil {
		return x.CommitCount
	}
	return 0
}

func (x *DataRequest) GetSignatureCount() uint64 {
	if x != nil {
		return x.SignatureCount
	}
	return 0
}

type PayLoad struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainId          uint64 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	ContractAddress  string `protobuf:"bytes,2,opt,name=contract_address,json=contractAddress,proto3" json:"contract_address,omitempty"`
	FunctionSignture string `protobuf:"bytes,3,opt,name=function_signture,json=functionSignture,proto3" json:"function_signture,omitempty"`
	Output           []byte `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *PayLoad) Reset() {
	*x = PayLoad{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mycelia_mycelia_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayLoad) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayLoad) ProtoMessage() {}

// Deprecated: Use PayLoad.ProtoReflect.Descriptor instead.
func (*PayLoad) Descriptor() ([]byte, []int) {
	return file_mycelia_mycelia_types_proto_rawDescGZIP(), []int{1}
}

func (x *PayLoad) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *PayLoad) GetContractAddress() string {
	if x != nil {
		return x.ContractAddress
	}
	return ""
}

func (x *PayLoad) GetFunctionSignture() string {
	if x != nil {
		return x.FunctionSignture
	}
	return ""
}

func (x *PayLoad) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_mycelia_mycelia_types_proto protoreflect.FileDescriptor

var file_mycelia_mycelia_types_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x6d, 0x79, 0x63, 0x65, 0x6c, 0x69, 0x61, 0x2f, 0x6d, 0x79, 0x63, 0x65, 0x6c, 0x69,
	0x61, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6d,
	0x79, 0x63, 0x65, 0x6c, 0x69, 0x61, 0x2e, 0x6d, 0x79, 0x63, 0x65, 0x6c, 0x69, 0x61, 0x1a, 0x11,
	0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x2f, 0x61, 0x6d, 0x69, 0x6e, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x14, 0x67, 0x6f, 0x67, 0x6f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x67,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf3, 0x01, 0x0a, 0x0b, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x02, 0x69, 0x64, 0x12, 0x32, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f,
	0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x79, 0x63, 0x65, 0x6c,
	0x69, 0x61, 0x2e, 0x6d, 0x79, 0x63, 0x65, 0x6c, 0x69, 0x61, 0x2e, 0x50, 0x61, 0x79, 0x4c, 0x6f,
	0x61, 0x64, 0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x2f, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x6d, 0x79,
	0x63, 0x65, 0x6c, 0x69, 0x61, 0x2e, 0x6d, 0x79, 0x63, 0x65, 0x6c, 0x69, 0x61, 0x2e, 0x53, 0x54,
	0x41, 0x54, 0x55, 0x53, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x27, 0x0a, 0x0f, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74,
	0x75, 0x72, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x3a, 0x23, 0x8a, 0xe7, 0xb0, 0x2a, 0x1e, 0x6d,
	0x79, 0x63, 0x65, 0x6c, 0x69, 0x61, 0x2f, 0x78, 0x2f, 0x6d, 0x79, 0x63, 0x65, 0x6c, 0x69, 0x61,
	0x2f, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x22, 0xb4, 0x01,
	0x0a, 0x07, 0x50, 0x61, 0x79, 0x4c, 0x6f, 0x61, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12,
	0x2b, 0x0a, 0x11, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x69, 0x67, 0x6e,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x66, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x74, 0x75, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x3a, 0x1e, 0x8a, 0xe7, 0xb0, 0x2a, 0x19, 0x6d, 0x79, 0x63, 0x65, 0x6c,
	0x69, 0x61, 0x2f, 0x78, 0x2f, 0x6d, 0x79, 0x63, 0x65, 0x6c, 0x69, 0x61, 0x2f, 0x50, 0x61, 0x79,
	0x4c, 0x6f, 0x61, 0x64, 0x2a, 0x31, 0x0a, 0x06, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x12, 0x0d,
	0x0a, 0x09, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x08, 0x41, 0x54, 0x54, 0x45, 0x53, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x53,
	0x49, 0x47, 0x4e, 0x45, 0x44, 0x10, 0x02, 0x42, 0xa0, 0x01, 0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x2e,
	0x6d, 0x79, 0x63, 0x65, 0x6c, 0x69, 0x61, 0x2e, 0x6d, 0x79, 0x63, 0x65, 0x6c, 0x69, 0x61, 0x42,
	0x0a, 0x54, 0x79, 0x70, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x20, 0x63,
	0x6f, 0x73, 0x6d, 0x6f, 0x73, 0x73, 0x64, 0x6b, 0x2e, 0x69, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x6d, 0x79, 0x63, 0x65, 0x6c, 0x69, 0x61, 0x2f, 0x6d, 0x79, 0x63, 0x65, 0x6c, 0x69, 0x61, 0xa2,
	0x02, 0x03, 0x4d, 0x4d, 0x58, 0xaa, 0x02, 0x0f, 0x4d, 0x79, 0x63, 0x65, 0x6c, 0x69, 0x61, 0x2e,
	0x4d, 0x79, 0x63, 0x65, 0x6c, 0x69, 0x61, 0xca, 0x02, 0x0f, 0x4d, 0x79, 0x63, 0x65, 0x6c, 0x69,
	0x61, 0x5c, 0x4d, 0x79, 0x63, 0x65, 0x6c, 0x69, 0x61, 0xe2, 0x02, 0x1b, 0x4d, 0x79, 0x63, 0x65,
	0x6c, 0x69, 0x61, 0x5c, 0x4d, 0x79, 0x63, 0x65, 0x6c, 0x69, 0x61, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x10, 0x4d, 0x79, 0x63, 0x65, 0x6c, 0x69,
	0x61, 0x3a, 0x3a, 0x4d, 0x79, 0x63, 0x65, 0x6c, 0x69, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_mycelia_mycelia_types_proto_rawDescOnce sync.Once
	file_mycelia_mycelia_types_proto_rawDescData = file_mycelia_mycelia_types_proto_rawDesc
)

func file_mycelia_mycelia_types_proto_rawDescGZIP() []byte {
	file_mycelia_mycelia_types_proto_rawDescOnce.Do(func() {
		file_mycelia_mycelia_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_mycelia_mycelia_types_proto_rawDescData)
	})
	return file_mycelia_mycelia_types_proto_rawDescData
}

var file_mycelia_mycelia_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_mycelia_mycelia_types_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_mycelia_mycelia_types_proto_goTypes = []interface{}{
	(STATUS)(0),         // 0: mycelia.mycelia.STATUS
	(*DataRequest)(nil), // 1: mycelia.mycelia.DataRequest
	(*PayLoad)(nil),     // 2: mycelia.mycelia.PayLoad
}
var file_mycelia_mycelia_types_proto_depIdxs = []int32{
	2, // 0: mycelia.mycelia.DataRequest.payload:type_name -> mycelia.mycelia.PayLoad
	0, // 1: mycelia.mycelia.DataRequest.status:type_name -> mycelia.mycelia.STATUS
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_mycelia_mycelia_types_proto_init() }
func file_mycelia_mycelia_types_proto_init() {
	if File_mycelia_mycelia_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mycelia_mycelia_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_mycelia_mycelia_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayLoad); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mycelia_mycelia_types_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_mycelia_mycelia_types_proto_goTypes,
		DependencyIndexes: file_mycelia_mycelia_types_proto_depIdxs,
		EnumInfos:         file_mycelia_mycelia_types_proto_enumTypes,
		MessageInfos:      file_mycelia_mycelia_types_proto_msgTypes,
	}.Build()
	File_mycelia_mycelia_types_proto = out.File
	file_mycelia_mycelia_types_proto_rawDesc = nil
	file_mycelia_mycelia_types_proto_goTypes = nil
	file_mycelia_mycelia_types_proto_depIdxs = nil
}
